---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: badapp
spec:
  selector:
    matchLabels:
      app: badapp
  template:
    metadata:
      labels:
        app: badapp
    spec:
      containers:
        - name: badapp
          imagePullPolicy: Always
          image: palnabarun/badapp
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: badapp-config
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 2        # default 10, minimum 1
            timeoutSeconds: 2       # default 1, minimum 1
            successThreshold: 1     # default 1, minimum 1
            failureThreshold: 3     # default 3, minimum 1
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5        # default 10, minimum 1
            timeoutSeconds: 2       # default 1, minimum 1
            successThreshold: 1     # default 1, must be 1 for liveness
            failureThreshold: 3     # default 3, minimum 1
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      terminationGracePeriodSeconds: 60
