apiVersion: v1
kind: Service
metadata:
  labels:
    app: badapp
  name: badapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: badapp
  type: ClusterIP
